### ISSUE TITLE
vertaisarviointi

### ISSUE THREAD

**Issue by sakorh** [Rokirok/reservations#1]
Sovelluksen käyttöliittymä on selkeä, visuaalisesti miellyttävä ja siinä on helppo navigoida. Toimiviksi mainitut ominaisuudet toimivat odotetulla tavalla. Koodi ja tietokanta myös asianmukaisesti toteutettu. Pienenä huomiona se, että kun sovellukseen luo uuden työntekijä-käyttäjän, lukee tämän tiedoissa roolina virheellisesti pääkäyttäjä, mutta tämä varmaankin korjaantuu sovelluksen kehityksen edetessä. Rekisteröitymisestä voisi ehkä tehdä käyttäjäystävällisempää tuomalla jotenkin ilmi jo ennen salasanan syöttämistä, mitkä ovat sen minimivaatimukset. 
Asiakkaan näkökulmasta katsottuna voisi olla kätevämpää, jos varausta tehdessä näkisi yhdellä kertaa kaikkien eri kampaajien vapaat ajat sen sijaan, että ennen vapaiden aikojen näkemistä tulisi sokkona valita joku tietty kampaaja. Varausta tehdessä voisi myös olla hyvä olla jonkinlainen 'takaisin'-nappi, jolla pääsisi esim. kampaajan valinnasta takaisin toimipisteen valintaan.

**Comment by EetuHuttula** [comment]
- Kun varasin aikaa kohteeseen kumpula hiusten värjäyksen kumpulaan sain ajan hiusten leikkuuseen meilahteen.
- Formeissa ei ole "takaisin päin" nappulaa joka olisi mielekkäämpi tapa navigoida sivustoa.
- henkilökunnalle nappula hankala löytää, väri voisi olla selkeämpi.
- rekisteröinnin jälkeen en voi kirjautua sisään käyttäjällä.
- Ehkä ei kannata antaa mahdollisuutta poistaa pääkäyttäjää (admin_test).

Muuten koodi on hyvin jaettu pieniin osiin mikä tekee siitä mukavan lukea.
Hakemisto on erittäin selkeä.
